Events:
    Platform.RenderOutput:
       - {Handler: \Apps\Webiny\Backend\Layout\Php\Handlers\HtmlCleanup, Priority: 101}
    Platform.HandleRequest:
       - {Handler: \Apps\Webiny\Backend\Layout\Php\Handlers\RenderApp}


Parsers:
    Tags:
        # UI module
        form-inline: Webiny.Apps.Webiny.UI.Components.FormInline
        form-horizontal: Webiny.Apps.Webiny.UI.Components.FormHorizontal
        form-group: Webiny.Apps.Webiny.UI.Components.FormGroup
        form: [Webiny.Apps.Webiny.UI.Components.Form, [form]]
        input: [Webiny.Apps.Webiny.UI.Components.Input, [input]]
        checkbox-group: Webiny.Apps.Webiny.UI.Components.CheckboxGroup
        switch: Webiny.Apps.Webiny.UI.Components.Switch
        switch-button: Webiny.Apps.Webiny.UI.Components.SwitchButton
        a: [Webiny.Apps.Webiny.UI.Components.Link, [a]]
        grid-12: Webiny.Apps.Webiny.UI.Components.Grid12
        grid-6: Webiny.Apps.Webiny.UI.Components.Grid6
        grid-4: Webiny.Apps.Webiny.UI.Components.Grid4
        grid-2: Webiny.Apps.Webiny.UI.Components.Grid2
        modal: Webiny.Apps.Webiny.UI.Components.Modal
        modal-header: Webiny.Apps.Webiny.UI.Components.ModalHeader
        modal-body: Webiny.Apps.Webiny.UI.Components.ModalBody
        modal-footer: Webiny.Apps.Webiny.UI.Components.ModalFooter

        # Table module
        table: [Webiny.Apps.Webiny.Table.Components.Table, [table]]
        tbody: [Webiny.Apps.Webiny.Table.Components.Tbody, [tbody]]
        thead: [Webiny.Apps.Webiny.Table.Components.Thead, [thead]]
        tr: [Webiny.Apps.Webiny.Table.Components.Tr, [tr]]
        th: [Webiny.Apps.Webiny.Table.Components.Th, [th]]
        td: [Webiny.Apps.Webiny.Table.Components.Td, [td]]
        tfoot: [Webiny.Apps.Webiny.Table.Components.Tfoot, [tfoot]]