Events:
    Platform.RenderOutput:
       - {Handler: \Apps\Webiny\Backend\Layout\Php\Handlers\HtmlCleanup, Priority: 101}
    Platform.HandleRequest:
       - {Handler: \Apps\Webiny\Backend\Layout\Php\Handlers\RenderApp}


Parsers:
    Tags:
        form-inline: FormInline
        form-horizontal: FormHorizontal
        form-group: FormGroup
        form: Form
        input: Input
        checkbox-group: CheckboxGroup
        switch: Switch
        switch-button: SwitchButton
        many2one: Many2One
        a: Link
        table: Table
        tbody: Tbody
        thead: Thead
        tr: Tr
        th: Th
        td: Td
        tfoot: Tfoot
        grid-12: Grid12
        grid-6: Grid6
        grid-4: Grid4
        grid-2: Grid2
        modal: Modal
        modal-header: ModalHeader
        modal-body: ModalBody
        modal-footer: ModalFooter

    # Use native HTML tags instead of react components
    Skip:
        - SwitchButton
        - Checkbox