Platform:
    WebPath: http://platform.app:8000
    ApiPath: /api
    AbsPath: __DIR__/../..
    AppsPath: /Apps
    Backend:
        Prefix: admin
    ErrorReporting: true
    Bootstrap:
        App: Core
        Module: Layout
        Component: App

Database:
    Host: 127.0.0.1:27017
    Name: webiny-platform

Mongo:
    Services:
        Webiny:
            Class: \Webiny\Component\Mongo\Mongo
            Arguments:
                Host: 127.0.0.1:27017
                Database: webiny-platform
    ResultClass: \Webiny\Component\Mongo\MongoResult

Entity:
    Database: Webiny

Rest:
    Api:
        CompilePath: __DIR__/../../Cache/Rest
        Environment: development
        Router:
            Class: \Apps\{app}\{area}\{module}\Php\Services\{service}
            Path: /api/{app}/{area}/{module}/{service}
            Normalize: true

Services:
    Smarty:
        Factory: \Webiny\Platform\Tools\TemplateEngine
        Method: getInstance

Storage:
    Services:
        Root:
            Class: \Webiny\Component\Storage\Storage
            Arguments:
                Driver:
                    Object: \Webiny\Component\Storage\Driver\Local\LocalStorageDriver
                    ObjectArguments:
                        - __DIR__/../..
        Apps:
            Class: \Webiny\Component\Storage\Storage
            Arguments:
                Driver:
                    Object: \Webiny\Component\Storage\Driver\Local\LocalStorageDriver
                    ObjectArguments:
                        - __DIR__/../../Apps
        Build:
            Class: \Webiny\Component\Storage\Storage
            Arguments:
                Driver:
                    Object: \Webiny\Component\Storage\Driver\Local\LocalStorageDriver
                    ObjectArguments:
                        - __DIR__/../../Public/Build
                        - ''
                        - false
                        - true